### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by lukeinator42** [zzw922cn/Automatic_Speech_Recognition#24]
I was wondering if a pretrained model could be made available. Specifically, I was hoping for the model used to generate the librispeech examples in the readme.

Thanks!

**Comment by zzw922cn** [comment]
Hi, i'll show you a pretrained model in a few days(about 1 or 2 weeks), i am sorry i can't get the pretrained model now, for my computer server is far away from where i am.

**Comment by zzw922cn** [comment]
@lukeinator42

**Comment by lukeinator42** [comment]
@zzw922cn Ok, thanks! sounds good

**Comment by stingerpk** [comment]
Hello @zzw922cn 
If you could share your pre-trained model, that would be very helpful. Thank you

**Comment by zzw922cn** [comment]
@stingerpk ok, but my pretrained model is slightly different from the github project. I will show in my github later.

**Comment by zzw922cn** [comment]
@stingerpk @lukeinator42 hi, sorry to reply you. My pretrained model now is not owned by me. So I have no copyright to release it, however, if you have any questions about this model, feel free to push your issues. Thank you for understanding!
