### ISSUE TITLE
package/lib requirements

### ISSUE THREAD

**Issue by bshao001** [zzw922cn/Automatic_Speech_Recognition#41]
I checked the requirements.txt, and it states that this project requires the following libraries or frameworks:

tabulate==0.7.7 
theano==0.9.0 
xlwt==1.2.0 

Is theano really required, what is that for? It will not be supported in the future. Therefore, I would like to confirm this.

Also, the other two packages look weird to me, what are they used for: creating tabular data, and excel file? Are they essential to this project?

**Comment by zzw922cn** [comment]
@bshao001 Hi, theano is not required! tabulate and xlwt is required for analysis. Thank you for correcting!

**Comment by bshao001** [comment]
@zzw922cn Thank you for the clarification.
