### ISSUE TITLE
Deep Speech 2 build_graph not called

### ISSUE THREAD

**Issue by dreamibor** [zzw922cn/Automatic_Speech_Recognition#42]
Hello, 

In the Deep Speech model that you defined in "models/deepSpeech2.py", the function build_graph was not called, this will result an error as following:
"AttributeError: 'DeepSpeech2' object has no attribute 'var_trainable_op' "
I compared with the "dynamic_brnn.py", you should add "self.build_graph(args, maxTimeSteps)" in the class initialiser.

Thanks,

**Comment by zzw922cn** [comment]
@dreamibor thank you, ill fix it soon!
