### ISSUE TITLE
why is "if er / batch_size == 1.0:" necessary?

### ISSUE THREAD

**Issue by chenkailuvcode** [zzw922cn/Automatic_Speech_Recognition#43]
Hi! I found "if er / batch_size == 1.0:" is necessary in the *_train.py file. If I delete it, then the errorRate will stay at 1.0 forever. I am very confused. Why this happens? 3ks~

**Comment by zzw922cn** [comment]
@chenkailuvcode in some cases, the loss would be a nan number. So I add this line of code to avoid getting stuck.
