### ISSUE TITLE
About the audiolab in this project

### ISSUE THREAD

**Issue by bshao001** [zzw922cn/Automatic_Speech_Recognition#45]
Sorry to bother you again. But I really would like to know how important is this external lib: scikits.audiolab to this project. 

I want to use python 3, and I see that your code is not that hard to be modified to adapt python 3. However, the scikits.audiolab only supports python 2. Therefore, I have this question. Can I find any replacement for that? Or where (what part of functions) is the lib used in your project?

Thank you very much!

**Comment by zzw922cn** [comment]
@bshao001 hi, audiolab is used to read audio data, you can also use **librosa** intead. Best wishes!

**Comment by bshao001** [comment]
@zzw922cn Thank you very much. I will give it a try.

**Comment by zzw922cn** [comment]
@bshao001 you are welcome
