### ISSUE TITLE
中文语音识别

### ISSUE THREAD

**Issue by yyhlvdl** [zzw922cn/Automatic_Speech_Recognition#47]
@zzw922cn我看了代码，发现timit文件是把英文分解成音素或者字符级别，来结合语音特征向量进行训练。libri文件是根据英文对应的数字编码自然转化为向量来训练的。那么，中文呢？我理解的是好像是直接把语音特征向量和中文的单词进行对应训练。也许是我代码理解的还不全面，但是，作者可以回答下我的这个疑惑吗？

**Comment by zzw922cn** [comment]
@john81529 你好，我了解到的现在中文做法比较多的是使用语音特征作为输入，使用汉字作为输出标签，这样可以避免拼音的解码操作，当然也有先把句子分词之后以单词作为标签，这样个人感觉会更合理。

**Comment by john81529** [comment]
谢谢。我最近看了百度的deepspeech2,他们就是用汉字直接作为标签的，虽然说不知道他们怎么又使用上语言模型的。不过，苗亚杰博士给出了例子，目前正在研究中。
