### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by kenyeung128** [zzw922cn/Automatic_Speech_Recognition#56]
Hi, after i followed the instruction and install the packages, i got errors as below when running train command, any idea? thanks.

  File "/usr/local/lib/python3.5/dist-packages/SpeechValley-1.0.0-py3.5.egg/speechvalley/utils/visualization.py", line 24
    print 'Just mono files'
                          ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by zzw922cn** [comment]
In python 3.5, "print" should be used along "()".

**Comment by hiteshpaul** [comment]
As mentioned by @zzw922cn , in python 3.x, print should be enclosed in parentheses. Closing this.

**Comment by kenyeung128** [comment]
however, the code is generated by the installer? and i am using python 3.5, what shall i do?

**Comment by friendmine** [comment]
just add parentheses and rerun python setup.py install
