### ISSUE TITLE
Hello, @zzw922cn, when I run speechvalley/main/madarian_train.py, error as follow , how can I slove it?

### ISSUE THREAD

**Issue by KyrieHee** [zzw922cn/Automatic_Speech_Recognition#70]
`NotADirectoryError: [Errno 20] Not a directory: '/home/data/data_thchs30/cha/train/B6_286.wav.trn'
`

**Comment by wujsy** [comment]
@KyrieHee, hi, have you successed to train madarian model yet? could you share your script for prepreocess dataset?
